# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c08c0cf8b75bcf31c96d3ce3932e574ecd3b1f7bbbe1548b916ea0eec7f56681edf84daa3e19050e1a2967c94fd6ce3216a7860642010da8bfc21835b295e2bd

test:
  secret_key_base: ce5f1ce401a678c061e7cd9df97e313e02f6a7c99729ba373cfe916f0e4f1b612b344cdc802ed2bc53caf15b027947f73787d81378859090e215e40806244970

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
